name: Push Production to HuggingFace



on:

  push:

    branches: [app_dev]



  # run this workflow manualy from the Actions tab

  workflow_dispatch:



jobs:

  sync-to-hub:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

        with:

          fetch-depth: 0

          lfs: true

      - name: Deploy Production (app_dev) to HuggingFace

        env:

          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: git push --force https://DF38:$HF_TOKEN@huggingface.co/spaces/spark-ds549/LibRAG app_dev:main
