name: Push Production to HuggingFace

on:

  push:

    branches: [dan_dev]

  workflow_dispatch:



jobs:

  sync-to-hub:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

        with:

          fetch-depth: 0

          lfs: true

      

      - name: Configure Git LFS

        run: |

          git lfs install

          git lfs pull

      

      - name: Deploy Production (dan_dev) to HuggingFace

        env:

          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: git push --force https://DF38:$HF_TOKEN@huggingface.co/spaces/spark-ds549/LibRAG/
